// Regenerates shared/assets.generated.ts from shared/assets/* (fonts subset to Latin, mascot downscaled).
const fs = require("fs");
const path = require("path");
const dir = path.join(__dirname, "..", "shared", "assets");
const b64 = (f) => fs.readFileSync(path.join(dir, f)).toString("base64");
const out = `/* eslint-disable */
// GENERATED by scripts/gen-assets.js — do not edit by hand.
export const FONT_REGULAR = "data:font/woff2;base64,${b64("Blibli-Regular.otf.woff2")}";
export const FONT_MEDIUM = "data:font/woff2;base64,${b64("Blibli-Medium.otf.woff2")}";
export const FONT_BOLD = "data:font/woff2;base64,${b64("Blibli-Bold.otf.woff2")}";
export const MASCOT_CHEER = "data:image/png;base64,${b64("friend-cheer.png")}";
`;
fs.writeFileSync(path.join(__dirname, "..", "shared", "assets.generated.ts"), out);
console.log("wrote shared/assets.generated.ts", out.length, "bytes");
